Geolocalisation
WildCodeSchool/toulouse-0219-java-metro pull request #13
Opened 2019-04-03 14:21 UTC by pandadod

2019-04-03 14:37 UTC, ghost approved these changes
ok pour les modifs

2019-04-03 15:17 UTC, bastienapp requested changes

2019-04-03 15:17 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/metro/MapsActivity.java
> +                    builder.setMessage("Oessit app must have access to your GPS. Please accept ! (or die !)");
Pas de texte en dur, ni temporaire (car il va être oublié !)

2019-04-04 07:18 UTC, bastienapp approved these changes

2019-04-04 07:18 UTC, merged