ajout de la distance user-metro
WildCodeSchool/toulouse-0219-java-metro pull request #21
Opened 2019-04-09 15:36 UTC by pandadod

bonne relecture ! XD

2019-04-09 16:22 UTC, SnxDubois approved these changes
Code relu. Pas d'erreur apparente

2019-04-10 07:30 UTC, bastienapp requested changes

2019-04-10 07:30 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/metro/AdapterStation.java
> +    Location locUser = new Location("");
Une varaible globale (déclarée en dehors d'une méthode) doit commencer par un m minuscule : mLocUser (MAJ + F6)

2019-04-10 07:30 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/metro/AdapterStation.java
> +        textDistance.setText(distanceInMeters + " meters");
ALT + Entrée, remplacer + par String.format (c'est fait automatiquement)
Et ensuite ALT + Entrée : entraide la chaîne hardcoded

2019-04-10 07:30 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/metro/Metro.java
> +                JSONArray geo_point_2d = (JSONArray) fields.get("geo_point_2d");
camelCase pour les variable, pas snake_case

2019-04-10 07:30 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/metro/Metro.java
> +                StationMetro stations = new StationMetro(stationName, latitude, longitude);
station au singulier (il n'y en a qu'une)

2019-04-10 08:01 UTC, bastienapp approved these changes

2019-04-10 08:01 UTC, merged