Snippet info
WildCodeSchool/toulouse-0219-java-metro pull request #23
Opened 2019-04-10 16:06 UTC by SnxDubois

2019-04-10 16:17 UTC, pandadod commented
ok

2019-04-11 07:02 UTC, bastienapp requested changes

2019-04-11 07:02 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/metro/CustomInfoMarkerAdapter.java
> +        if(!title.equals("")) {
il manque des espaces, toujours faire MAJ + CTRL + ALT + L

2019-04-11 07:02 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/metro/MapsActivity.java
> +    private Location locationUser = null;
variable globale commence par m minuscule : mLocationUser (MAJ + F6)

2019-04-11 07:42 UTC, bastienapp approved these changes

2019-04-11 07:42 UTC, merged