Stationfav
WildCodeSchool/toulouse-0219-java-metro pull request #42
Opened 2019-04-25 16:17 UTC by pandadod

2019-04-25 16:22 UTC, ghost reviewed
ok :)

2019-04-25 16:39 UTC, bastienapp requested changes

2019-04-25 16:39 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/metro/Favorites.java
> +        if (!(user == null)) {
user != null

2019-04-25 16:39 UTC, bastienwcs commented on app/src/main/res/values/strings.xml
> +    <string name="welcome">Welcome_</string>
Welcome_ ? Il faut le _ à la fin ?

2019-04-26 07:18 UTC, pandadod commented
corrections faites

2019-04-26 07:32 UTC, bastienapp approved these changes

2019-04-26 07:32 UTC, merged